#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Sep 21 00:03:48 PDT 2026
maven-metadata-spring-snapshots.xml.error=Could not transfer metadata org.springframework.boot\:spring-boot-starter-webmvc\:4.1.0-SNAPSHOT/maven-metadata.xml from/to spring-snapshots (https\://repo.spring.io/snapshot)\: repo.spring.io
maven-metadata-spring-snapshots.xml/@default-spring-snapshots-https\://repo.spring.io/snapshot/.lastUpdated=1789974228069
