spring.application.name=backend


spring.datasource.url=jdbc:postgresql://localhost:5432/ScholarSync
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

# Make sure this is a long, secure, random string in production!
jwt.secret=XmfJKK67fKYLVbpfZ8rsbC2+EfIw7Jgx6Am5IYfGeMo=
# Token validity in milliseconds (e.g., 24 hours = 86400000)
jwt.expiration=86400000
